#!/bin/sh

#  Copyright (c) 2005  Volker Grabsch, Matthias Pohl
#
#  Permission is hereby granted, free of charge, to any person obtaining
#  a copy of this software and associated documentation files (the
#  "Software"), to deal in the Software without restriction, including
#  without limitation the rights to use, copy, modify, merge, publish,
#  distribute, sublicense, and/or sell copies of the Software, and to
#  permit persons to whom the Software is furnished to do so, subject
#  to the following conditions:
#
#  The above copyright notice and this permission notice shall be
#  included in all copies or substantial portions of the Software.
# 
#  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
#  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
#  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
#  IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
#  CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
#  TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
#  SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.


if test -z "$1"
then
    echo
    echo "    make-crontab"
    echo "    ============"
    echo
    echo "    Manage different cronjobs with only one system user."
    echo
    echo
    echo "Installation:"
    echo "    $0 DESTDIR [MAKE]"
    echo
    echo "    (MAKE defaults to /usr/bin/make)"
    echo
    echo "Examples:"
    echo "    $0 /var/lib/make-crontab"
    echo "    $0 /var/lib/make-crontab /usr/local/bin/make"
    echo "    $0 ."
    echo
    exit 1
fi

mkdir -p "$1"
cd "$1"
DESTDIR="`pwd`"

if test -z "$2"
then
    MAKE="/usr/bin/make"
else
    MAKE="$2"
fi

echo "CREATE: $DESTDIR/crontab-make"
cat >"$DESTDIR/crontab-make" <<EOF
* * * * *  cd '$DESTDIR' && $MAKE >/dev/null
EOF

echo "CREATE: $DESTDIR/Makefile"
cat >"$DESTDIR/Makefile" <<EOF
#  Copyright (c) 2005  Volker Grabsch, Matthias Pohl
#
#  Permission is hereby granted, free of charge, to any person obtaining
#  a copy of this software and associated documentation files (the
#  "Software"), to deal in the Software without restriction, including
#  without limitation the rights to use, copy, modify, merge, publish,
#  distribute, sublicense, and/or sell copies of the Software, and to
#  permit persons to whom the Software is furnished to do so, subject
#  to the following conditions:
#
#  The above copyright notice and this permission notice shall be
#  included in all copies or substantial portions of the Software.
# 
#  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
#  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
#  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
#  IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
#  CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
#  TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
#  SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.


SOURCES=\$(wildcard crontab-*)
RESULT=crontab

default: \$(RESULT)

\$(RESULT): \$(SOURCES)
	# create crontab
	( \\
	echo "#________________________________________" ; \\
	echo "#  This file is automatically generated.  DO NOT EDIT!" ; \\
	for FILE in \$+ ; do \\
	    echo "#"; \\
	    echo "#________________________________________" ; \\
	    echo "#+++ \$\$FILE +++" ; \\
	    echo "#"; \\
	    cat "\$\$FILE" ; \\
	done \\
	) > "\$@"
	# install crontab
	crontab "\$@"
EOF
